require 'contacts/base'
require 'contacts/json_picker'
require 'contacts/gmail'
require 'contacts/hotmail'
require 'contacts/yahoo'
require 'contacts/plaxo'
require 'contacts/aol'
require 'contacts/mailru'
